version: "3.4"

volumes:
  postgres_data:


services:
  app:
    container_name: app
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
    working_dir: /app
    env_file:
      - .env

  db:
    image: postgres:14.4
    container_name: db
    restart: always
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sublime
      - POSTGRES_HOST_AUTH_METHOD=trust
