apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: sublime:latest
          imagePullPolicy: Never
          workingDir: /app/src
          command: ["/bin/sh", "-c"]
          args: ["celery -A core worker -l info"]
          envFrom:
            - configMapRef:
                name: app-config
