apiVersion: v1
kind: ConfigMap
metadata:
    name: elasticmq-config
data:
    elasticmq.conf: |
        include classpath("application.conf")

        queues {
        sublime {
            defaultVisibilityTimeout = 30 seconds
            delay = 0 seconds
            receiveMessageWait = 0 seconds
        }
        }

        messages-storage {
        enabled = true
        }
