apiVersion: v1
kind: Service
metadata:
  name: elasticmq
spec:
  selector:
    app: elasticmq
  ports:
    - name: port1
      protocol: TCP
      port: 9324
      targetPort: 9324
    - name: port2
      protocol: TCP
      port: 9325
      targetPort: 9325
